#!/bin/sh

# While using commands use the full path to that path because it is a security feature

fullpath="$(pwd)/$file"

while read file
do
    case "$1" in
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && /usr/bin/rm "$file" && notify-send "$file deleted." ;;
        "w")
            $HOME/.local/bin/setbg "$file" ;;
        "r")
            /usr/bin/convert -rotate 90 "$file" "$file" ;;
        "R")
            /usr/bin/convert -rotate -90 "$file" "$file" ;;
        "i") notify-send "File information" "$(mediainfo "$file")" ;;
        esac
    done
