#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

## Custom BASH PROMPT
PS1='\e[2;34m[\e[0m\e[1;32m\u\e[0m\e[0;31m@\e[0m\e[1;35m\H\e[0m  \w\e[2;34m]\e[0m$ '

## Bash alias file
[ -f $HOME/.config/shell/aliasrc ] && source $HOME/.config/shell/aliasrc

## bash completion
[ -f /etc/bash_completion ] && source /etc/bash_completion
