#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

ssh-agent dwm

# while loop for dwm; a hot reload for pywal wallpaper colorscheme change
while type dwm >/dev/null ; do dwm && continue || break ; done
